//
// Created by Марсель on 23.08.2025.
//

#ifndef POSITIONCONSTANT_H
#define POSITIONCONSTANT_H

#define CONST static constexpr auto
namespace elements::coord {
    CONST X = 1300;
    CONST Y = 900;

    CONST MODE_BUTTON_Y = 500;
    CONST MODE_BUTTON_SIZE_X = 300;
    CONST MODE_BUTTON_START_X = 50;
    CONST MODE_BUTTON_END_X = X - MODE_BUTTON_START_X - MODE_BUTTON_SIZE_X;

    CONST CHANGE_PAGE_BUTTON_INDENT = 5;
    CONST CHANGE_PAGE_BUTTON_X = CHANGE_PAGE_BUTTON_INDENT;
    CONST CHANGE_PAGE_BUTTON_Y = CHANGE_PAGE_BUTTON_INDENT;

    CONST CHOOSE_MODE_BUTTON_INDENT = 30;
    CONST CHOOSE_MODE_BUTTON_HEIGHT_OF_MODES = 100;

    CONST PLAYER_COUNT_BUTTON_Y = 160;
    CONST PLAYER_COUNT_BUTTON_INDENT = 240;
    CONST PLAYER_COUNT_BUTTON_SIZE_X = 186;

    CONST TRACK_SIZE = 20;
    CONST SLIDER_DICE_COUNT_X = 300;
    CONST SLIDER_DICE_COUNT_Y = 300;
    CONST SLIDER_WIGHT = 50;
}

#undef CONST
#endif //POSITIONCONSTANT_H
